library(sf)
library(raster)
library(exactextractr)
library(dplyr)
library(readxl)
library(cowplot)
library(ggplot2)
library(scales)
library(tidyr)
library(tidyverse)
library(rgeos)
library(gdalUtils)
library(chron)
library(nngeo)
library(strex)
library(rgee)
library(data.table)
library(qgisprocess)
library(gdata)
library(FactoMineR)
library(factoextra)
library(maps)  
library(mapdata)
library(maptools)
library(grid)
library(randomForestSRC)


ee_Initialize(email = 'giacomo.falchetta@gmail.com', drive = TRUE)
